<a href="https://colab.research.google.com/github/Manasa23BEIS123/AIML-12-Week-Program/blob/W1-Manasa/W1D2_Pandas_Data_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)
print("Setup completed successfully!")

Pandas version: 2.2.3
NumPy version: 2.1.3
Setup completed successfully!

In [ ]:
import pandas as pd

# Real Indian state population data based on Census 2011
data = {
    "State": [
        "Uttar Pradesh", "Maharashtra", "Bihar", "West Bengal",
        "Madhya Pradesh", "Tamil Nadu", "Rajasthan", "Karnataka",
        "Gujarat", "Andhra Pradesh", "Odisha", "Telangana",
        "Kerala", "Jharkhand", "Assam"
    ],
    "Population": [
        199812341, 112374333, 104099452, 91276115,
        72626809, 72147030, 68548437, 61095297,
        60439692, 49577103, 41974218, 35003674,
        33406061, 32988134, 31205576
    ],
    "Area_km2": [
        240928, 307713, 94163, 88752, 308252,
        130060, 342239, 191791, 196024, 162968,
        155707, 112077, 38863, 79716, 78438
    ]
}

df = pd.DataFrame(data)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

print("\nData Types:")
print(df.dtypes)

print("\nFirst 10 rows:")
display(df.head(10))

Dataset loaded successfully!
Shape: (15, 3)

Data Types:
State         object
Population     int64
Area_km2       int64
dtype: object

First 10 rows:

            State  Population  Area_km2
0   Uttar Pradesh   199812341    240928
1     Maharashtra   112374333    307713
2           Bihar   104099452     94163
3     West Bengal    91276115     88752
4  Madhya Pradesh    72626809    308252
5      Tamil Nadu    72147030    130060
6       Rajasthan    68548437    342239
7       Karnataka    61095297    191791
8         Gujarat    60439692    196024
9  Andhra Pradesh    49577103    162968

In [ ]:
# Filter: Select states with population greater than 50 million
high_population = df[df["Population"] > 50000000]

print("States with population greater than 50 million:")
display(high_population)

States with population greater than 50 million:

            State  Population  Area_km2
0   Uttar Pradesh   199812341    240928
1     Maharashtra   112374333    307713
2           Bihar   104099452     94163
3     West Bengal    91276115     88752
4  Madhya Pradesh    72626809    308252
5      Tamil Nadu    72147030    130060
6       Rajasthan    68548437    342239
7       Karnataka    61095297    191791
8         Gujarat    60439692    196024

In [ ]:
# GroupBy: Calculate the average population by area category
df["Area_Category"] = pd.cut(
    df["Area_km2"],
    bins=[0, 100000, 200000, 400000],
    labels=["Small", "Medium", "Large"]
)

grouped = df.groupby("Area_Category", observed=True)["Population"].mean()

print("Average population by area category:")
display(grouped)

Average population by area category:

Area_Category
Small     5.859507e+07
Medium    5.337284e+07
Large     1.133405e+08
Name: Population, dtype: float64

In [ ]:
# Create a second DataFrame with region information
region_data = pd.DataFrame({
    "State": [
        "Uttar Pradesh", "Maharashtra", "Bihar", "West Bengal",
        "Madhya Pradesh", "Tamil Nadu", "Rajasthan", "Karnataka",
        "Gujarat", "Andhra Pradesh", "Odisha", "Telangana",
        "Kerala", "Jharkhand", "Assam"
    ],
    "Region": [
        "North", "West", "East", "East",
        "Central", "South", "North", "South",
        "West", "South", "East", "South",
        "South", "East", "North-East"
    ]
})

# Merge: Combine the population DataFrame with region information using State
merged_df = pd.merge(df, region_data, on="State", how="left")

print("Merged DataFrame:")
display(merged_df.head(10))

Merged DataFrame:

            State  Population  Area_km2 Area_Category   Region
0   Uttar Pradesh   199812341    240928         Large    North
1     Maharashtra   112374333    307713         Large     West
2           Bihar   104099452     94163         Small     East
3     West Bengal    91276115     88752         Small     East
4  Madhya Pradesh    72626809    308252         Large  Central
5      Tamil Nadu    72147030    130060        Medium    South
6       Rajasthan    68548437    342239         Large    North
7       Karnataka    61095297    191791        Medium    South
8         Gujarat    60439692    196024        Medium     West
9  Andhra Pradesh    49577103    162968        Medium    South

In [ ]:
# Pivot Table: Summarize total population by region and area category
pivot = pd.pivot_table(
    merged_df,
    values="Population",
    index="Region",
    columns="Area_Category",
    aggfunc="sum",
    fill_value=0
)

print("Population by region and area category:")
display(pivot)

Population by region and area category:

/tmp/ipykernel_1112/2945746377.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot = pd.pivot_table(

Area_Category      Small     Medium      Large
Region
Central                0          0   72626809
East           228363701   41974218          0
North                  0          0  268360778
North-East      31205576          0          0
South           33406061  217823104          0
West                   0   60439692  112374333

In [ ]:
# Export: Save the cleaned DataFrame as CSV and Parquet files

# Save as CSV
merged_df.to_csv("cleaned_indian_population.csv", index=False)

# Save as Parquet
merged_df.to_parquet("cleaned_indian_population.parquet", index=False)

print("CSV and Parquet files created successfully!")

CSV and Parquet files created successfully!

In [ ]:
# Compare: Check the file sizes of CSV and Parquet

import os

csv_size = os.path.getsize("cleaned_indian_population.csv")
parquet_size = os.path.getsize("cleaned_indian_population.parquet")

print(f"CSV file size: {csv_size} bytes")
print(f"Parquet file size: {parquet_size} bytes")

if csv_size > parquet_size:
    print("Parquet file is smaller than CSV.")
else:
    print("CSV file is smaller than Parquet.")

CSV file size: 625 bytes
Parquet file size: 3886 bytes
CSV file is smaller than Parquet.

In [ ]:
print("========== W1D2 PANDAS DATA MANIPULATION ==========")

print("\n1. Dataset Shape:")
print(df.shape)

print("\n2. Filtered Data:")
display(high_population)

print("\n3. GroupBy Result:")
display(grouped)

print("\n4. Merged DataFrame:")
display(merged_df.head(10))

print("\n5. Pivot Table:")
display(pivot)

print("\n6. Export Files:")
print("cleaned_indian_population.csv")
print("cleaned_indian_population.parquet")

print("\n========== W1D2 COMPLETED ==========")

========== W1D2 PANDAS DATA MANIPULATION ==========

1. Dataset Shape:
(15, 4)

2. Filtered Data:

            State  Population  Area_km2
0   Uttar Pradesh   199812341    240928
1     Maharashtra   112374333    307713
2           Bihar   104099452     94163
3     West Bengal    91276115     88752
4  Madhya Pradesh    72626809    308252
5      Tamil Nadu    72147030    130060
6       Rajasthan    68548437    342239
7       Karnataka    61095297    191791
8         Gujarat    60439692    196024

3. GroupBy Result:

Area_Category
Small     5.859507e+07
Medium    5.337284e+07
Large     1.133405e+08
Name: Population, dtype: float64

4. Merged DataFrame:

            State  Population  Area_km2 Area_Category   Region
0   Uttar Pradesh   199812341    240928         Large    North
1     Maharashtra   112374333    307713         Large     West
2           Bihar   104099452     94163         Small     East
3     West Bengal    91276115     88752         Small     East
4  Madhya Pradesh    72626809    308252         Large  Central
5      Tamil Nadu    72147030    130060        Medium    South
6       Rajasthan    68548437    342239         Large    North
7       Karnataka    61095297    191791        Medium    South
8         Gujarat    60439692    196024        Medium     West
9  Andhra Pradesh    49577103    162968        Medium    South

5. Pivot Table:

Area_Category      Small     Medium      Large
Region
Central                0          0   72626809
East           228363701   41974218          0
North                  0          0  268360778
North-East      31205576          0          0
South           33406061  217823104          0
West                   0   60439692  112374333

6. Export Files:
cleaned_indian_population.csv
cleaned_indian_population.parquet

========== W1D2 COMPLETED ==========

In [ ]:
from google.colab import files

files.download("cleaned_indian_population.csv")
files.download("cleaned_indian_population.parquet")

In [ ]:
from google.colab import files

files.download("cleaned_indian_population.parquet")