<a href="https://colab.research.google.com/github/Manasa23BEIS123/AIML-12-Week-Program/blob/W1-Manasa/W1D3_Data_Loading_Cleaning_Inspection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# W1D3: Data Loading, Cleaning & Inspection

import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 2.2.3
NumPy version: 2.1.3

In [ ]:
# Load the Indian population dataset
url = "https://raw.githubusercontent.com/Manasa23BEIS123/W1D1-Numpy/main/W1D2/cleaned_indian_population.csv"

df = pd.read_csv(url)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

print("\nData types:")
print(df.dtypes)

print("\nFirst 10 rows:")
display(df.head(10))

Dataset loaded successfully!
Shape: (15, 5)

Data types:
State            object
Population        int64
Area_km2          int64
Area_Category    object
Region           object
dtype: object

First 10 rows:

            State  Population  Area_km2 Area_Category   Region
0   Uttar Pradesh   199812341    240928         Large    North
1     Maharashtra   112374333    307713         Large     West
2           Bihar   104099452     94163         Small     East
3     West Bengal    91276115     88752         Small     East
4  Madhya Pradesh    72626809    308252         Large  Central
5      Tamil Nadu    72147030    130060        Medium    South
6       Rajasthan    68548437    342239         Large    North
7       Karnataka    61095297    191791        Medium    South
8         Gujarat    60439692    196024        Medium     West
9  Andhra Pradesh    49577103    162968        Medium    South

In [ ]:
# Check for missing values
print("Missing values:")
print(df.isnull().sum())

# Check for duplicate rows
print("\nNumber of duplicate rows:", df.duplicated().sum())

Missing values:
State            0
Population       0
Area_km2         0
Area_Category    0
Region           0
dtype: int64

Number of duplicate rows: 0

In [ ]:
# Clean column names for easier use
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print("Cleaned column names:")
print(df.columns.tolist())

Cleaned column names:
['state', 'population', 'area_km2', 'area_category', 'region']

In [ ]:
# Remove duplicate rows
before = len(df)

df = df.drop_duplicates()

after = len(df)

print("Rows before removing duplicates:", before)
print("Rows after removing duplicates:", after)
print("Duplicates removed:", before - after)

Rows before removing duplicates: 15
Rows after removing duplicates: 15
Duplicates removed: 0

In [ ]:
# Fill missing numeric values with the column median
numeric_columns = df.select_dtypes(include=np.number).columns

for column in numeric_columns:
    df[column] = df[column].fillna(df[column].median())

print("Missing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
state            0
population       0
area_km2         0
area_category    0
region           0
dtype: int64

In [ ]:
# Inspect the cleaned dataset
print("Cleaned dataset shape:", df.shape)

print("\nCleaned dataset:")
display(df.head(10))

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

Cleaned dataset shape: (15, 5)

Cleaned dataset:

            state  population  area_km2 area_category   region
0   Uttar Pradesh   199812341    240928         Large    North
1     Maharashtra   112374333    307713         Large     West
2           Bihar   104099452     94163         Small     East
3     West Bengal    91276115     88752         Small     East
4  Madhya Pradesh    72626809    308252         Large  Central
5      Tamil Nadu    72147030    130060        Medium    South
6       Rajasthan    68548437    342239         Large    North
7       Karnataka    61095297    191791        Medium    South
8         Gujarat    60439692    196024        Medium     West
9  Andhra Pradesh    49577103    162968        Medium    South

Data types:
state            object
population        int64
area_km2          int64
area_category    object
region           object
dtype: object

Missing values:
state            0
population       0
area_km2         0
area_category    0
region           0
dtype: int64

In [ ]:
# Save the cleaned dataset as CSV
output_file = "W1D3_cleaned_dataset.csv"

df.to_csv(output_file, index=False)

print(f"Cleaned dataset saved successfully as: {output_file}")

Cleaned dataset saved successfully as: W1D3_cleaned_dataset.csv

In [ ]:
# Validate the cleaned dataset

# Test 1: Dataset should not be empty
assert len(df) > 0, "Dataset is empty"

# Test 2: No duplicate rows should remain
assert df.duplicated().sum() == 0, "Duplicate rows found"

# Test 3: No missing values should remain in numeric columns
numeric_columns = df.select_dtypes(include=np.number).columns
assert df[numeric_columns].isnull().sum().sum() == 0, "Missing numeric values found"

print("All validation tests passed successfully!")

All validation tests passed successfully!

In [ ]:
from google.colab import files

files.download("W1D3_cleaned_dataset.csv")