<a href="https://colab.research.google.com/github/Manasa23BEIS123/AIML-12-Week-Program/blob/feat%2Faiml-W3-Manasa/W3D5_Hyperparameter_Tuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# W3D5: Hyperparameter Tuning — GridSearch & RandomSearch

import numpy as np
import pandas as pd

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import (
    train_test_split,
    GridSearchCV,
    RandomizedSearchCV
)
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

print("Libraries imported successfully")

Libraries imported successfully

In [2]:
# Load the Breast Cancer classification dataset

data = load_breast_cancer(as_frame=True)
df = data.frame

print("Dataset loaded successfully")
print("Shape:", df.shape)

display(df.head())

Dataset loaded successfully
Shape: (569, 31)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [3]:
# Separate features (X) and target (y)

X = df.drop("target", axis=1)
y = df["target"]

print("Features shape:", X.shape)
print("Target shape:", y.shape)
print("\nNumber of features:", X.shape[1])
print("Target classes:", data.target_names)

Features shape: (569, 30)
Target shape: (569,)

Number of features: 30
Target classes: ['malignant' 'benign']

In [4]:
# Split the dataset into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training features:", X_train.shape)
print("Testing features :", X_test.shape)
print("Training target  :", y_train.shape)
print("Testing target   :", y_test.shape)

Training features: (455, 30)
Testing features : (114, 30)
Training target  : (455,)
Testing target   : (114,)

In [6]:
# Standardize the features

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Feature scaling completed successfully")
print("Scaled training shape:", X_train_scaled.shape)
print("Scaled testing shape :", X_test_scaled.shape)

Feature scaling completed successfully
Scaled training shape: (455, 30)
Scaled testing shape : (114, 30)

In [7]:
# Create the Support Vector Machine (SVM) model

svm_model = SVC()

print("SVM model created successfully")
print(svm_model)

SVM model created successfully
SVC()

In [8]:
# Define hyperparameters for GridSearchCV

param_grid = {
    "C": [0.1, 1, 10, 100],
    "gamma": ["scale", "auto"],
    "kernel": ["rbf"]
}

grid_search = GridSearchCV(
    SVC(),
    param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

grid_search.fit(X_train_scaled, y_train)

print("GridSearchCV completed successfully")
print("Best parameters:", grid_search.best_params_)
print("Best cross-validation accuracy:", grid_search.best_score_)

GridSearchCV completed successfully
Best parameters: {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}
Best cross-validation accuracy: 0.9736263736263737

In [9]:
# Define hyperparameter distributions for RandomizedSearchCV

param_dist = {
    "C": [0.01, 0.1, 1, 10, 100, 1000],
    "gamma": ["scale", "auto", 0.001, 0.01, 0.1, 1],
    "kernel": ["rbf"]
}

random_search = RandomizedSearchCV(
    SVC(),
    param_distributions=param_dist,
    n_iter=10,
    cv=5,
    scoring="accuracy",
    random_state=42,
    n_jobs=-1
)

random_search.fit(X_train_scaled, y_train)

print("RandomizedSearchCV completed successfully")
print("Best parameters:", random_search.best_params_)
print("Best cross-validation accuracy:", random_search.best_score_)

RandomizedSearchCV completed successfully
Best parameters: {'kernel': 'rbf', 'gamma': 0.01, 'C': 10}
Best cross-validation accuracy: 0.9802197802197803

In [10]:
# Compare the best results from GridSearchCV and RandomizedSearchCV

print("GridSearchCV Results")
print("--------------------")
print("Best Parameters:", grid_search.best_params_)
print("Best CV Accuracy:", grid_search.best_score_)

print("\nRandomizedSearchCV Results")
print("-------------------------")
print("Best Parameters:", random_search.best_params_)
print("Best CV Accuracy:", random_search.best_score_)

GridSearchCV Results
--------------------
Best Parameters: {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}
Best CV Accuracy: 0.9736263736263737

RandomizedSearchCV Results
-------------------------
Best Parameters: {'kernel': 'rbf', 'gamma': 0.01, 'C': 10}
Best CV Accuracy: 0.9802197802197803

In [11]:
# Get the best SVM model from GridSearchCV

best_svm = grid_search.best_estimator_

# Make predictions on the test set
y_pred = best_svm.predict(X_test_scaled)

# Calculate accuracy
test_accuracy = accuracy_score(y_test, y_pred)

print("Best SVM Test Accuracy:", test_accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Best SVM Test Accuracy: 0.9736842105263158

Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.98      0.96        42
           1       0.99      0.97      0.98        72

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114


Confusion Matrix:
[[41  1]
 [ 2 70]]

In [12]:
# Compare the test performance of both tuned models

grid_best_model = grid_search.best_estimator_
random_best_model = random_search.best_estimator_

grid_predictions = grid_best_model.predict(X_test_scaled)
random_predictions = random_best_model.predict(X_test_scaled)

grid_accuracy = accuracy_score(y_test, grid_predictions)
random_accuracy = accuracy_score(y_test, random_predictions)

comparison = pd.DataFrame({
    "Method": ["GridSearchCV", "RandomizedSearchCV"],
    "Best Parameters": [
        grid_search.best_params_,
        random_search.best_params_
    ],
    "CV Accuracy": [
        grid_search.best_score_,
        random_search.best_score_
    ],
    "Test Accuracy": [
        grid_accuracy,
        random_accuracy
    ]
})

display(comparison)

,Method,Best Parameters,CV Accuracy,Test Accuracy
0,GridSearchCV,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.973626,0.973684
1,RandomizedSearchCV,"{'kernel': 'rbf', 'gamma': 0.01, 'C': 10}",0.980220,0.982456

In [13]:
# Simple automated tests for the tuned SVM workflow

assert X_train_scaled.shape == (455, 30)
assert X_test_scaled.shape == (114, 30)

assert len(y_train) == 455
assert len(y_test) == 114

assert grid_search.best_estimator_ is not None
assert random_search.best_estimator_ is not None

assert 0 <= grid_accuracy <= 1
assert 0 <= random_accuracy <= 1

print("All automated tests passed successfully!")

All automated tests passed successfully!

## W3D5 Summary

- Loaded and prepared the Breast Cancer classification dataset.
- Standardized features using StandardScaler.
- Created an SVM classifier.
- Tuned SVM hyperparameters using GridSearchCV.
- Tuned SVM hyperparameters using RandomizedSearchCV.
- Compared cross-validation and test accuracy of both tuning methods.
- Evaluated the best SVM using accuracy, classification report, and confusion matrix.
- Ran automated tests successfully.

### Key Learning

GridSearchCV evaluates all specified hyperparameter combinations, while
RandomizedSearchCV evaluates a selected number of randomly chosen combinations.
Both methods help identify better hyperparameters and improve model performance.